# -*- coding: utf-8 -*-
"""ola_mundo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nPr8HEATUJsa0x-viGuUnIsXumfGRXJD
"""

# prompt: print("Olá, m

print("Olá, mundo")